print("I wake up")
print("I straighten my hair")
print("I get dressed and go to school")
print("I study")
Mystudytime = print(5+3)
print("I get on the bus and revise")
Myrevision = print(3+2)
print("i get home")
print("I do homework")
Myhomework = print(1+2)
print("I go to sleep")
Mysleeptime = print(6+3)
print('Next day i do the same')
